name = "Ost Passage-Theater"
#description = "Accomplished actor, captivating with versatility and charisma."
#keywords = "Jake Gyllenhaal, actor, filmography, awards, versatile performances, Hollywood"
image = "jake.webp"
theme = "dark"
primary_color = "#ff6600"
text_align = "center"
gtag_id = "G-33WB8LVHR6"
base_url = "https://opt-t.github.io"

[[sections]]
#title = "Movies"
#description = "Here are some of my movies"
#direction = "column"
#item_style = "outline"
[[sections.items]]
title = "Nextcloud"
#description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://opt-team.moeh.re"
[[sections.items]]
title = "Veranstaltungen"
#description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://ost-passage-theater.de/veranstaltungen/"
[[sections.items]]
title = "IF'25 Foto Upload"
description = "Nextcloud\00_Plenum\2 - VEREIN\2 - Vereinsbuchhaltung\Wirtschaftsplan-Institutionelle Förderung\IF 2025\Fotos für IF '25"
url = "https://opt-team.moeh.re/f/379144"

[[sections]]
title = "Nextcloud Links"
#description = "Look for me on these websites"
direction = "row"
item_style = "outline"
[[sections.items]]
title = "Kalender"
url = "https://opt-team.moeh.re/apps/calendar/"
[[sections.items]]
title = "Photos"
url = "https://opt-team.moeh.re/apps/photos/"
[[sections.items]]
title = "akt. Prots"
url = "https://opt-team.moeh.re/f/373993"
