name = "OPT"
#description = "Accomplished actor, captivating with versatility and charisma."
#keywords = "Jake Gyllenhaal, actor, filmography, awards, versatile performances, Hollywood"
#image = "jake.webp"
theme = "dark"
primary_color = "#ff6600"
text_align = "center"
#gtag_id = "G-33WB8LVHR6"
base_url = "https://opt-t.github.io"

[[sections]]
title = "OPT"
#description = "Here are some of my movies"
direction = "column"
item_style = "outline"

[[sections.items]]
title = "Veranstaltungen"
#description = "A groundbreaking romantic drama challenging societal expectations"
url = "https://ost-passage-theater.de/veranstaltungen/"

[[sections]]
title = "Nextcloud Direkt"
#description = "Look for me on these websites"
#direction = "row"
direction = "column"
item_style = "filled"
[[sections.items]]
title = "IF25 Fotos"
#description = "Nextcloud\00_Plenum\2 - VEREIN\2 - Vereinsbuchhaltung\Wirtschaftsplan-Institutionelle Förderung\IF 2025\Fotos für IF '25"
url = "https://opt-team.moeh.re/f/379144"
[[sections.items]]
title = "Kalender"
url = "https://opt-team.moeh.re/apps/calendar/"
[[sections.items]]
title = "Fotos"
url = "https://opt-team.moeh.re/apps/photos/"
[[sections.items]]
title = "Protokolle"
url = "https://opt-team.moeh.re/f/373993"
[[sections.items]]
title = "Wurzel"
url = "https://opt-team.moeh.re"
